config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :states
  resources :legislators
  root to: 'states#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/legislator.rb
class Legislator < ApplicationRecord
  belongs_to :state
end

app/models/propublica_api_caller.rb
require 'pry-byebug'

class PropublicaApiCaller

  @attributes = ["member_id", "first_name", "middle_name", "last_name", "party", "title", "chamber", "term_start", "term_end", "missed_votes_pct", "date_of_birth", "next_election", "total_votes", "missed_votes", "office", "phone", "votes_with_party_pct", "twitter_account", "facebook_account", "youtube_account", "govtrack_id", "votesmart_id", "state"]
  @chambers = ["senate", "house"]

  def self.update_legislators
    Legislator.destroy_all

    @chambers.each do |chamber|
      member_data = HTTParty.get("https://api.propublica.org/congress/v1/115/#{chamber}/members.json", :headers => { 'Content-Type' => 'application/json', 'X-API-Key' => ENV["PROPUBLICA_API_KEY"] })

      member_data["results"][0]["members"].each do |legislator_json|
        legislator = Legislator.new
        @attributes.each do |attribute|
          if attribute == "member_id"
            legislator.member_id = legislator_json["id"]
          elsif attribute != "state"
            legislator.send("#{attribute}=", legislator_json[attribute])
          else
            state = State.find_by(abbreviation: legislator_json["state"])
            legislator.state_id = state.id
          end
        end
        legislator.save!
      end
    end
  end
end

app/models/state.rb
class State < ApplicationRecord
  has_many :legislators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/legislators_controller.rb
class LegislatorsController < ApplicationController

  def index
    @legislators = Legislator.all
  end

  def show
    @legislator = Legislator.find(params[:id])
  end

  private

  def legislator_params
    params.require(:legislator).permit(:first_name, :middle_name, :last_name, :state, :party, :title, :chamber, :term_start, :term_end, :missed_votes_pct, :state_id, :date_of_birth, :next_election, :total_votes, :missed_votes, :office, :phone, :votes_with_party_pct, :twitter_account, :facebook_account, :youtube_account, :govtrack_id, :votesmart_id)
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController

  def index
    @states = State.all
  end

  def show
    @state = State.find(params[:id])
  end


  private
  
  def state_params
    params.require(:state).permit(:name, :abbreviation, :state_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/legislators_helper.rb
module LegislatorsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CongressVotes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/legislators/index.html.erb
<br>
<% @legislators.each do |legislator| %>
  <%= link_to legislator.name, legislator_path(legislator) %><br> 

<% end %>

app/views/legislators/show.html.erb
<%= @legislator.first_name %>
<%= @legislator.last_name %>
(<%= @legislator.party %>)<br>
<%= @legislator.title %><br><br>
ID: <%= @legislator.member_id %><br>
Votes with Party Percentage: <%= @legislator.votes_with_party_pct %>%<br>
Total Votes: <%= @legislator.total_votes %><br>
Missed Votes: <%= @legislator.missed_votes %><br>
Percentage of Votes Missed: <%= @legislator.missed_votes_pct %>%<br><br>
Phone: <%= @legislator.phone %><br>
Office Address: <%= @legislator.office %><br>
Date of Birth: <%= @legislator.date_of_birth %><br><br>

Social<br><br>
<a href="https://twitter.com/<%= @legislator.twitter_account %>">Twitter</a><br>
<a href="https://www.facebook.com/<%= @legislator.facebook_account %>/">Facebook</a> <br>
<a href="https://www.youtube.com/user/<%= @legislator.youtube_account %>">Youtube</a><br>

<a href="https://www.govtrack.us/congress/members/<%= @legislator.first_name %>_<%= @legislator.last_name %>/<%= @legislator.govtrack_id %>">Govtrack</a>
<br>
<a href="https://votesmart.org/candidate/biography/<%= @legislator.votesmart_id %>/<%= @legislator.first_name %>-<%= @legislator.last_name %>"> Votesmart</a>


<br><br><br>

Next Election: <b><%= @legislator.next_election %></b><br>

app/views/states/index.html.erb
<br>
<% @states.each do |state| %>
  <%= link_to state.name, state_path(state) %>
  <br>
<% end %>

app/views/states/show.html.erb
<%= @state.name %><br><br>
<% @state.legislators.each do |legislator| %>
  <%= link_to legislator.first_name + " " + legislator.last_name, legislator_path(legislator) %>
  (<%= legislator.party %>)
  <%= legislator.title %>
  <br>
<% end %>